Added Order and OrderItem entities
andrii-subash/book-store pull request #10
Opened 2023-09-25 18:50 UTC by andrii-subash

2023-09-26 15:28 UTC, Ivan95kos requested changes
Good job overall!

2023-09-26 15:28 UTC, Ivan95kos commented on src/main/java/book/store/controller/OrderController.java
> +                                                      @PathVariable Long itemId,
formatting

2023-09-26 15:28 UTC, Ivan95kos commented on src/main/java/book/store/service/impl/CartItemServiceImpl.java
> +            //if the book is in the shopping cart,
Instead of leaving a comment, create private methods with appropriate names and move the logic there so that it is clear what is being done

2023-09-26 15:28 UTC, Ivan95kos commented on src/main/java/book/store/service/impl/UserServiceImpl.java
> +        if (user.getEmail().startsWith("admin")) {
It's better to create a separate endpoint that will create admins than to hard code around like this

2023-09-28 17:26 UTC, kozhukhovsky approved these changes

2023-09-29 07:40 UTC, merged