added test for shopping cart and cart item services, controllers and …
andrii-subash/book-store pull request #13
Opened 2023-10-10 14:34 UTC by andrii-subash

…repositories

2023-10-10 14:43 UTC, andrii-subash commented
![image](https://github.com/andrii-subash/book-store/assets/126912806/3d324258-e9d2-4a7f-b506-d22d16bdf128)

2023-10-10 17:38 UTC, Ivan95kos requested changes
Good job overall!

2023-10-10 17:38 UTC, Ivan95kos commented on src/main/java/book/store/service/impl/CartItemServiceImpl.java
> +        }
useless logic, 
What is the reason that you did it?
If it is after the tests, it is better to rewrite the tests than to change the basic logic
```suggestion
            cartItem.setQuantity(requestDto.getQuantity());
            cartItemRepository.save(cartItem);
```

2023-10-11 11:50 UTC, okuzan approved these changes

2023-10-11 12:22 UTC, merged